using Documenter
using ToQUBO

# Set up to run docstrings with jldoctest
DocMeta.setdocmeta!(ToQUBO, :DocTestSetup, :(using ToQUBO); recursive = true)

const GENERATED_EXAMPLES_HEADER = "<!-- Generated by docs/make.jl -- do not edit directly. -->\n\n"

const CANONICAL_QUBO_EXAMPLES = [
    (
        title = "Knapsack",
        source = "examples/knapsack.md",
        target = "examples/knapsack",
        description = "a small binary model with a capacity constraint that compiles to a compact QUBO.",
    ),
    (
        title = "Prime Factorization",
        source = "examples/integer_factorization.md", # legacy ToQUBO filename
        target = "examples/prime_factorization",      # QUBO.jl URL slug
        description = "a bounded integer model that highlights automatic encoding and quadratization.",
    ),
    (
        title = "Portfolio Optimization",
        source = "examples/portfolio_optimization.md",
        target = "examples/portfolio_optimization",
        description = "a small continuous allocation model that shows how bounded encodings affect the compiled problem size.",
    ),
]

# GitHub Actions sets GITHUB_REF_TYPE="tag" on tag pushes; map that to the
# Documenter "stable" folder, defaulting to "dev" for branch and PR builds.
canonical_qubo_docs_version() = get(ENV, "GITHUB_REF_TYPE", "") == "tag" ? "stable" : "dev"

function canonical_qubo_docs_url(
    path::AbstractString = "";
    version::AbstractString = canonical_qubo_docs_version(),
)
    base = "https://juliaqubo.github.io/QUBO.jl/QUBO.jl/$version"

    return isempty(path) ? "$base/" : "$base/$path/"
end

function write_if_changed(path::AbstractString, content::AbstractString)
    if isfile(path) && read(path, String) == content
        return nothing
    end

    mkpath(dirname(path))

    open(path, "w") do io
        write(io, content)
    end

    return nothing
end

function generate_examples_pages!()
    version = canonical_qubo_docs_version()

    release_note = if version == "dev"
        "These links follow the `QUBO.jl` development docs until the next coordinated release. Release builds of this manual point to `stable`."
    else
        "These links point to the latest released `QUBO.jl` documentation."
    end

    bullets = join(
        [
            "- [$(entry.title)]($(canonical_qubo_docs_url(entry.target; version))), $(entry.description)"
            for entry in CANONICAL_QUBO_EXAMPLES
        ],
        "\n",
    )

    write_if_changed(
        joinpath(@__DIR__, "src", "examples.md"),
        string(
            GENERATED_EXAMPLES_HEADER,
            "# Examples in QUBO.jl\n\n",
            "Application-oriented examples for the JuliaQUBO ecosystem now live in the\n",
            "[`QUBO.jl` documentation](", canonical_qubo_docs_url(; version), "), which serves as the canonical\n",
            "entry point for workflows that combine the compiler, drivers, and tooling\n",
            "packages.\n\n",
            "`ToQUBO.jl` keeps the package-specific workflow and reference material in this\n",
            "manual. For a local walkthrough of building and solving a model with\n",
            "`ToQUBO.Optimizer`, see [Running a Model](@ref).\n\n",
            release_note, "\n\n",
            "The current example pages in `QUBO.jl` are:\n\n",
            bullets, "\n",
        ),
    )

    for entry in CANONICAL_QUBO_EXAMPLES
        write_if_changed(
            joinpath(@__DIR__, "src", entry.source),
            string(
                GENERATED_EXAMPLES_HEADER,
                "# ", entry.title, "\n\n",
                "This page is kept as a compatibility entry for readers following older\n",
                "`ToQUBO.jl` example links.\n\n",
                "The canonical version now lives in the `QUBO.jl` documentation:\n\n",
                "- [", entry.title, "](", canonical_qubo_docs_url(entry.target; version), ")\n\n",
                "For package-specific workflow guidance, see [Running a Model](@ref).\n",
                "For the current ecosystem examples index, see [Examples in QUBO.jl](@ref).\n",
            ),
        )
    end

    return nothing
end

generate_examples_pages!()

makedocs(;
    modules  = [ToQUBO],
    doctest  = true,
    clean    = true,
    warnonly = [:missing_docs, :cross_references],
    format   = Documenter.HTML( #
        sidebar_sitename = false,
        mathengine       = Documenter.KaTeX(
            Dict(
                :macros => Dict(raw"\set" => raw"\left\lbrace{#1}\right\rbrace")
            )
        ),
        assets = [ #
            "assets/extra_styles.css",
            "assets/favicon.ico",
            # asset("https://tikzjax.com/v1/fonts.css"; class = :css),
            # asset("https://tikzjax.com/v1/tikzjax.js"; class = :js),
        ]
    ),
    sitename = "ToQUBO.jl",
    authors  = "Pedro Maciel Xavier and Pedro Ripper and Tiago Andrade and Joaquim Dias Garcia and David E. Bernal Neira",
    pages    = [ # 
        "Home"   => "index.md",
        "Manual" => [ #
            "Getting Started"   => "manual/1-start.md",
            "Running a Model"   => "manual/2-model.md",
            "Gathering Results" => "manual/3-results.md",
            "Compiler Settings" => "manual/4-settings.md"
        ],
        "Examples" => "examples.md",
        hide("examples/knapsack.md"),
        hide("examples/integer_factorization.md"),
        hide("examples/portfolio_optimization.md"),
        "Booklet" => [ #
            "Introduction"    => "booklet/1-intro.md",
            "QUBO"            => "booklet/2-qubo.md",
            "PBO"             => "booklet/3-pbo.md",
            "Encoding"        => "booklet/4-encoding.md",
            "Virtual Mapping" => "booklet/5-virtual.md",
            "The Compiler"    => "booklet/6-compiler.md",
            "Solvers"         => "booklet/7-solvers.md",
            "Appendix"        => "booklet/8-appendix.md",
        ]
    ],
    workdir = @__DIR__,
)

if "--skip-deploy" ∈ ARGS
    @warn "Skipping deployment"
else
    deploydocs(repo = raw"github.com/JuliaQUBO/ToQUBO.jl.git", push_preview = true)
end
