function test_docs()
    @testset "Docs" begin
        docs_dir = normpath(joinpath(@__DIR__, "..", "..", "docs", "src"))
        generated_pages = [
            joinpath(docs_dir, "examples.md"),
            joinpath(docs_dir, "examples", "knapsack.md"),
            joinpath(docs_dir, "examples", "integer_factorization.md"),
            joinpath(docs_dir, "examples", "portfolio_optimization.md"),
        ]

        for page in generated_pages
            contents = read(page, String)

            @test startswith(
                contents,
                "<!-- Generated by docs/make.jl -- do not edit directly. -->\n\n",
            )
        end
    end

    return nothing
end
