function test_docs()
    docs_dir = normpath(joinpath(@__DIR__, "..", "..", "docs", "src"))

    @testset "Docs" begin
        generated_pages = [
            joinpath(docs_dir, "examples.md"),
            joinpath(docs_dir, "examples", "knapsack.md"),
            joinpath(docs_dir, "examples", "integer_factorization.md"),
            joinpath(docs_dir, "examples", "portfolio_optimization.md"),
        ]

        for page in generated_pages
            contents = replace(read(page, String), "\r\n" => "\n")

            @test startswith(
                contents,
                "<!-- Generated by docs/make.jl -- do not edit directly. -->\n\n",
            )
        end
    end

    @testset "Penalty settings docs" begin
        settings_page =
            read(joinpath(docs_dir, "manual", "4-settings.md"), String)

        @test occursin("### Changing Penalty Values", settings_page)
        @test occursin("Attributes.ConstraintPenaltyScale()", settings_page)
        @test occursin("Attributes.SlackVariableEncodingPenaltyHint()", settings_page)
        @test occursin("ToQUBO-specific settings", settings_page)
    end

    return nothing
end
