include("compiler/compiler.jl")
include("compat.jl")
include("docs.jl")
include("constraint_reformulation_docs.jl")
include("encoding/encoding.jl")
include("virtual/virtual.jl")
include("model/model.jl")
include("wrapper/wrapper.jl")
include("attributes/attributes.jl")
include("reformulation.jl")
include("feasibility.jl")
include("qoblib_benchmark.jl")
include("dense_npp_profile.jl")
include("slack_resolution_analysis.jl")
include("slack_resolution_docs.jl")

function test_unit()
    @testset "⊚ Unit Tests" verbose = true begin
        test_encoding_methods()
        test_compiler()
        test_compat()
        test_docs()
        test_constraint_reformulation_docs()
        test_virtual()
        test_model()
        test_wrapper()
        test_attributes()
        test_reformulation_metadata()
        test_feasibility()
        test_qoblib_benchmark_pilot()
        test_dense_npp_profile_benchmark()
        test_slack_resolution_analysis()
        test_slack_resolution_docs()
    end

    return nothing
end
