name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x64
          - version: '1'
            os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v1
      #   with:
      #     cache: 'pip'
      # - run: pip install -r requirements.txt
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
        with: 
          project: "./src/Anneal.jl"
      - uses: julia-actions/julia-runtest@v1
        with: 
          project: "./src/Anneal.jl"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      # Future: Add Code Cov
      # - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v1
      #   with:
      #     file: lcov.info
